# Generated by Django 4.2.7 on 2023-11-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('track_file_url', models.URLField()),
                ('cover_image_url', models.URLField(blank=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
